@startuml
' Se concreta va bene così (perchè?)... ma se abstract? ;)
class Animale {
    - String nome
    - int età
    + void emettiVerso()
}

class Cane {
    + void abbaia()
}

class Gatto {
    + void faLeFusa()
}

Animale <|-- Cane
Animale <|-- Gatto
@enduml
