@startuml
:FirstActor: as a1
:Second Actor: as a2
:Client:
:SubClient:

rectangle system {
    (eat)
    usecase lu as "
    login utente
    --
    E.P.: se account non esiste
    "
    (crea profilo) as cp
    (jump)
    (estrai chiavi)
    (open the door) as ot
}

Client <|-- SubClient
(estrai chiavi) <.. ot : <<include>>
a1 -> ot
a2 -- ot
a2 -- lu
lu <.. cp : <<extend>>




@enduml