@startuml
' si poteva anche fare con relazioni bidirezionali,
' ma è altamente sconsigliato

class Ordine {
    - int numeroOrdine
    - Date data
    - double totale
    + void aggiungiProdotto()
}

class Cliente {
    - String nome
    - String email
    + void effettuaOrdine()
}

class Prodotto {
    - String nomeProdotto
    - double prezzo
}

Cliente "1" --> "0..*" Ordine : effettua
Ordine "1" --> "1..*" Prodotto : contiene
@enduml
