@startuml
class Studente {
    - int matricola
    - String nome
    - String cognome
}

class Corso {
    - String codiceCorso
    - String nomeCorso
}

class Docente {
    - String nome
    - String materia
}

Studente "1" --> "0..*" Corso : frequenta
Corso "1" -- "1" Docente : tenutoDa
@enduml
