@startuml
abstract class Piatto {
    - String nome
    + {abstract} prepara(): void
    + setNome(): void
}

class PrimoPiatto {
    - Sugo[] sugo
}

class SecondoPiatto  {
}

class Contorno  {
}

class Dolce {
}

class Sugo {
}

class Cuoco {
    + void cucina(Piatto piatto)
}

Piatto <|-- PrimoPiatto
Piatto <|-- SecondoPiatto
Piatto <|-- Contorno
Piatto <|-- Dolce
Sugo --|> Piatto
PrimoPiatto "1"--> "1..*" Sugo : usa

@enduml
